AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An application for getting geolocalized product prices by supermarket.

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        GetData:
          Type: Api
          Properties:
            Path: /prices
            Method: get

Outputs:
  GetDataApi:
    Description: API Gateway endpoint URL for Prod stage for GetData function.
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/prices/"
  GetDataFunction:
    Description: Hello World Lambda Function ARN.
    Value: !GetAtt GetDataFunction.Arn
  GetDataFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function.
    Value: !GetAtt GetDataFunctionRole.Arn